language: python
python:
  - "3.6"      # current default Python on Travis CI

addons:
  sonarcloud:
    organization: "andrewbessa"
    token:
      secure: "05980d80e5797828f69f1e84b65600be3c0d47b7"

install:
  - pip install -r requirements.txt
script:
  - pytest --cov=./ --cov-report xml
  - sonar-scanner